<?php

namespace comercial\ComercialBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OperacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperacionRepository extends EntityRepository
{
    public function BuscarVentaDiarias(\DateTime $date = null)
    {
        if($date == null)$date = new \DateTime('now');
        $query = $this->_em->createQuery('SELECT SUM(op.total) as ventaNeta FROM ComercialBundle:Operacion op WHERE op.fecha = :Fecha')
            ->setParameter('Fecha',$date->format('y-m-d'));
        return $query->getArrayResult();
    }
}
