<?php

namespace comercial\ComercialBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UtilidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilidadRepository extends EntityRepository
{
}
