<?php

namespace comercial\ComercialBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentaRepository extends EntityRepository
{
    public function BuscarVentaDiarias(\DateTime $date = null)
    {
        if($date == null)$date = new \DateTime('now');
        $query = $this->_em->createQuery('SELECT SUM(v.utilBrutaVenta) as utilidad FROM ComercialBundle:Venta v WHERE v.fecha = :Fecha')
            ->setParameter('Fecha',$date->format('y-m-d'));
        return $query->getArrayResult();
    }
}
